# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_Burg_beacon <- function(xS, pS) {
    .Call(`_beacon_C_Burg_beacon`, xS, pS)
}

#' C++ version of embed function
#'
#' @param x A numeric vector.
#' @param dimension A numeric.
#' @param numCores A numeric. A number of cores
#' @export
embedParallelCpp <- function(x, dimension, numCores) {
    .Call(`_beacon_embedParallelCpp`, x, dimension, numCores)
}

